name: Local tests ðŸ§ª
on: [push]

jobs:
  loom-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout ðŸ”ƒ
        uses: actions/checkout@v3

      - name: Installing Node.js ðŸ”¨
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies ðŸ”¨
        run: npm install

      - name: ðŸ§ª Loom Action test
        id: hello
        uses: ./
        with:
          pattern: 'mojang'
          behavior_pack_path: 'addon/behavior_pack'
          resource_pack_path: 'addon/resource_pack'
